### ISSUE TITLE
mean_inv substraction

### ISSUE THREAD

**Issue by amaik** [adamzjw/Probabilistic-matrix-factorization-in-Python#2]
This isn't an issue with the code but a question.

First of all thanks for putting this together. 
My question is: why is in line 65 and line 95 self.mean_inv subtracted? I cannot wrap my head around it and tried to reimplement it without that without success. I would be very happy if you could help me.

**Comment by adamzjw** [comment]
In practice, the predict targets, user ratings, are zero-centered. This trick helps the convergence and was implemented in the original matlab code.

In short, R_ij-mean = U_i ^T V_j, or R_ij = U_i ^T V_j + mean.
So U_i ^T V_j is mean subtracted.
